package com.milissa.corbaclient;

/**
* MiLissa/IdServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idserver.idl
* Monday, January 28, 2013 9:23:03 AM BRST
*/

public final class IdServerHolder implements org.omg.CORBA.portable.Streamable
{
  public IdServer value = null;

  public IdServerHolder ()
  {
  }

  public IdServerHolder (IdServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IdServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IdServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IdServerHelper.type ();
  }

}
